# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'VKServiceApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'Alamofire', '~> 4.7'
   pod 'SwiftyJSON'
   pod 'Kingfisher'
   pod 'RealmSwift'
   pod 'SwiftKeychainWrapper'
   pod 'Firebase/Core'
   pod 'Firebase/Database'
   pod 'Firebase/Auth'
   pod 'PinLayout'

  # Pods for VKServiceApp

end

target 'VKwidget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'Alamofire', '~> 4.7'
   pod 'SwiftyJSON'
   pod 'Kingfisher'
   pod 'RealmSwift'
   pod 'SwiftKeychainWrapper'
  # Pods for VKwidget

end